version: '3'

services:

  web_app:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: web_app
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - net

  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    volumes:
      - "C:/xampp/htdocs/jenkins-files/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "C:/xampp/htdocs/jenkins-files:/home"
    ports:
      - "8081:8080"
    networks:
      - net

networks:
  net: